name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          toolchain: stable
          profile: minimal
          components: "clippy, rustfmt"
          default: true
      - name: Clippy
        run: cargo clippy
      - name: Format
        run: cargo fmt -- --check
      - name: Test
        run: cargo test
